services:
  - type: web
    name: contact-book-app
    env: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
